### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mthouser**
Fixes issue where the SceneKit extensions will not compile. Should type be CGFloat instead of Float?

### CODE REVIEW

**Comment by mthouser** [comment]
It looks like my PR failed in CI. Not sure what is going on with my setup, but I had the opposite problem. 
 
According to Apple's Scene Kit documentation (https://developer.apple.com/library/mac/documentation/SceneKit/Reference/SceneKit_DataTypes/index.html#//apple_ref/c/tdef/SCNVector3) they define the initializer as 
    struct SCNVector3 { var x: CGFloat var y: CGFloat var z: CGFloat }

I was not able to get VectorMath+SceneKit.swift to compile on my Mac (OS X 10.10.2) with Xcode 6.1.1 without changing those references from `Float` to `CGFloat`.  But it looks like in the CI environment for this project, it works with `Float` but not `CGFloat`.

**Comment by nicklockwood** [comment]
I believe the problem is that Apple uses different float types on iOS vs OSX. Probably have to use an #ifdef to make it work on both.

**Comment by mthouser** [comment]
Thanks. I'm new to Cocoa development, so I apologize for the misunderstanding. 
Thank you for this library. It's just what I was looking for.

**Comment by nicklockwood** [comment]
No, problem at all. Thanks for highlighting the issue.

**Pull request closed without merging**
